POST http://localhost:3000/user/register
Content-Type: application/json

{
    "name":"Emirhan",
    "surname":"Karadeniz",
    "email": "admin@mail.com",
    "phone": "5076510758",
    "password": "123456"
}